[package]
name = "scherzo"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"

[features]
default = []
console = ["console-subscriber", "tokio/tracing"]

[dependencies]
harmony_rust_sdk = { git = "https://github.com/harmony-development/harmony_rust_sdk.git", branch = "master", features = ["gen_server", "gen_client"] }
sled = { version = "0.34.6", features = ["compression"] }
parking_lot = "0.11"
rand = "0.8"
flume = "0.10.7"
tokio = { version = "1.7", features = ["macros", "rt-multi-thread"] }
tokio-util = "0.6.7" 
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-appender = "0.1"
cached = "0.23"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
sha3 = "0.9"
urlencoding = "1.3"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls-native-roots", "stream"] }
infer = { version = "0.5", default-features = false }
dashmap = "4.0"
ahash = { version = "0.7", default-features = false }
console-subscriber = { git = "https://github.com/tokio-rs/console.git", branch = "main", optional = true }
webpage = { git = "https://github.com/yusdacra/webpage-rs.git", branch = "master", default-features = false }
lazy_static = "1.4"
smol_str = { version = "0.1", features = ["serde"] }

[profile.dev]
opt-level = 0
overflow-checks = true
debug-assertions = true
debug = false
codegen-units = 256
lto = false
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = false
codegen-units = 1
panic = 'abort'

[package.metadata.nix]
systems = ["x86_64-linux"]
app = true
build = true
library = true
devshell.packages = ["cargo-deny", "mkcert"]
cCompiler = "llvmPackages_12.clang"
nativeBuildInputs = ["lld_12"]
env.RUSTC_FORCE_INCREMENTAL = "1"

[package.metadata.nix.cachix]
name = "harmony"
key = "harmony.cachix.org-1:yv78QZHgS0UHkrMW56rccNghWHRz18fFRl8mWQ63M6E="