[package]
name = "scherzo"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"

[dependencies]
harmony_rust_sdk = { git = "https://github.com/harmony-development/harmony_rust_sdk.git", branch = "workaround/tls-fix", features = ["gen_server"] }
sled = { version = "0.34.6", features = ["compression"] }
parking_lot = "0.11"
rand = "0.8"
flume = "0.10"
tokio = { version = "1.6", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-appender = "0.1"
cached = "0.23"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
sha3 = "0.9"

[profile.dev]
opt-level = 0
overflow-checks = true
debug-assertions = true
debug = false
codegen-units = 256
lto = false
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = false
codegen-units = 1
panic = 'abort'

[package.metadata.nix]
systems = ["x86_64-linux"]
app = true
build = true
library = true

[package.metadata.nix.cachix]
name = "harmony"
key = "harmony.cachix.org-1:yv78QZHgS0UHkrMW56rccNghWHRz18fFRl8mWQ63M6E="
