[package]
name = "scherzo"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2018"

[dependencies]
harmony_rust_sdk = { git = "https://github.com/harmony-development/harmony_rust_sdk.git", branch = "master", features = ["gen_server"] }
sled = { version = "0.34.6", features = ["compression"] }
parking_lot = "0.11"
rand = "0.8"
tokio = { version = "1.2", features = ["macros", "rt-multi-thread"] }
simplelog = "0.9"

[profile.dev]
opt-level = 0
overflow-checks = true
debug-assertions = true
debug = false
codegen-units = 256
lto = false
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
overflow-checks = false
debug-assertions = false
debug = false
codegen-units = 1
panic = 'abort'