# The host where this server is hosted. Eg. `harmonyapp.io:2289` or `harmonyapp.io:4444`.
# A port must always be specified.
host = ""
# Whether to listen on `localhost` or `0.0.0.0` (useful for docker).
listen_on_localhost = true
# The port to listen on.
port = 2289
# Whether to support CORS requests. Should only be used for
# development purposes, since this allows everything.
cors_dev = false

[policy]
# Whether to disable ratelimits or not (useful when testing / benching).
disable_ratelimits = false
# Whether to disable registration and only allow it using admin generated tokens.
disable_registration = false
# Maximum amount of requests that should be processed concurrently.
# Note: you'll want to increase this if your server has 100+ members.
max_concurrent_requests = 512

[db]
# Path to a directory to put db backups in.
db_backup_path = "."
# Database in-memory cache limit in MiB.
db_cache_limit = 1024
# (sled only) whether to increase throughput at the cost of more storage usage.
sled_throughput_at_storage_cost = false

# HTTPS settings
[tls]
cert_file = "./cert"
key_file = "./key"

# Media settings
[media]
# Max upload length for files in MiB.
max_upload_length = 50
# Where to store media files.
media_root = "./media"

# Federation settings
[federation]
# Path to the federation key. This will be generated by the server automatically.
key = "./federation_key"
# Which hosts to allow. This takes priority over `host_block_list`.
host_allow_list = []
# Which hosts to block.
host_block_list = []