name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: harmony
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Enter devshell
      run: nix build .#devShell.x86_64-linux && source result 

    - name: Cargo Deny
      run: cargo deny check

    - name: Cache rust
      uses: Swatinem/rust-cache@v1

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy

    - name: Build
      run: cargo build --release

    - name: Compress binary
      run: upx target/release/scherzo

    - name: Upload release
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage target/release/scherzo

  update:
    needs: build
    name: Update Scherzo at harmonyapp.io
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - run: 'echo "$SSH_KEY" > key && chmod 600 key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.ACTIONS_SSH_KEY}}
      - run: 'echo "$KNOWN_HOSTS" > known_hosts && chmod 600 known_hosts'
        shell: bash
        env:
          KNOWN_HOSTS: ${{secrets.ACTIONS_SSH_KNOWN_HOSTS}}
      - run: 'ssh -i key -o UserKnownHostsFile=known_hosts "root@$SSH_HOST" update-scherzo'
        shell: bash
        env:
          SSH_HOST: ${{secrets.ACTIONS_SSH_HOST}}
      - name: Trigger integration testing
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.INTEGRATION_TEST_PAT }}
          repository: harmony-development/integration-testing
          event-type: dep-updated
