name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '**/*.nix'
      - 'nix/envrc'
      - 'flake.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends protobuf-compiler lld
    - name: Install rust
      run: rustup default 1.53.0 && rustup component add rustfmt clippy

    - name: Cache rust
      uses: Swatinem/rust-cache@v1

    - name: Install Cargo Deny
      run: cargo install --locked cargo-deny

    - name: Cargo Deny
      run: cargo deny check

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy

    - name: Build
      run: cargo build --release

    - name: Upload release
      if: github.event_name = 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage target/release/scherzo

  update:
    needs: build
    name: Update Scherzo at harmonyapp.io
    runs-on: ubuntu-latest
    if: github.event_name = 'push'
    steps:
      - run: 'echo "$SSH_KEY" > key && chmod 600 key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.ACTIONS_SSH_KEY}}
      - run: 'echo "$KNOWN_HOSTS" > known_hosts && chmod 600 known_hosts'
        shell: bash
        env:
          KNOWN_HOSTS: ${{secrets.ACTIONS_SSH_KNOWN_HOSTS}}
      - run: 'ssh -i key -o UserKnownHostsFile=known_hosts "root@$SSH_HOST" update-scherzo'
        shell: bash
        env:
          SSH_HOST: ${{secrets.ACTIONS_SSH_HOST}}
      - name: Trigger integration testing
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.INTEGRATION_TEST_PAT }}
          repository: harmony-development/integration-testing
          event-type: dep-updated
